### ISSUE TITLE
Can not run haste test with yoshi preset on latest haste version

### ISSUE THREAD

**Issue by Faradey27** [wix/haste#161]
```
[12:08:37] Starting 'copy-static-assets'...
{ Error: Cannot find module 'webpack/lib/Chunk'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/andriit/Documents/Projects/cashier-payments/cashier-payments-widget-fullstack/node_modules/extract-text-webpack-plugin/dist/index.js:17:14)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3) code: 'MODULE_NOT_FOUND' }
```

Started to receive this issue after todays morning update

advice in this issue solved the problem https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/485

But currently i m having webpack in my dev deps - but i should not)

**Comment by Faradey27** [comment]
Str provided via private messages

**Comment by Faradey27** [comment]
Problem was related to package-lock
